### ISSUE TITLE
 Solid : Missing packages

### ISSUE THREAD

**Issue by TheDevelolper** [nxext/nx-extensions#1099]
So when I used the generator I was getting errors: 

```
bun nx generate @nxext/solid:library --name=modula-ui-solid --no-interactive --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/eslint/plugin plugin.
    - .eslintrc.json: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json#overrides[1] » plugin:@nx/typescript': Cannot find module '@typescript-eslint/eslint-plugin'
  Require stack:
  - Q:\repos\product-menu\__placeholder__.js
  Referenced from: Q:\repos\product-menu\node_modules\@nx\eslint-plugin\src\index.js
      Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json#overrides[1] » plugin:@nx/typescript': Cannot find module '@typescript-eslint/eslint-plugin'
      Require stack:
      - Q:\repos\product-menu\__placeholder__.js
      Referenced from: Q:\repos\product-menu\node_modules\@nx\eslint-plugin\src\index.js
          at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
          at Function.resolve (node:internal/modules/helpers:190:19)
          at Object.resolve (Q:\repos\product-menu\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2372:46)
          at ConfigArrayFactory._loadPlugin (Q:\repos\product-menu\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3440:33)
          at ConfigArrayFactory._loadExtendedPluginConfig (Q:\repos\product-menu\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3259:29)
          at ConfigArrayFactory._loadExtends (Q:\repos\product-menu\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3180:29)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (Q:\repos\product-menu\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3121:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (Q:\repos\product-menu\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3066:20)
          at _normalizeObjectConfigData.next (<anonymous>)
```

I had to install 

```
bun i -D typescript-eslint
```

and it started working. However I also note that many of the packages are out dated. 

Are you still actively maintaining this project?

**Comment by DominikPieper** [comment]
Yes they are but since the birth of my daughter a bit slower 😅 we are a little behind with the latest version.

About your issue, none of the packages are tested with bun and I never used it yet. I don’t know how great it will work

**Comment by TheDevelolper** [comment]
I managed to get it working by installing them manually, congratulations to you with regards to your daughter 🎉

**Comment by DominikPieper** [comment]
Thank you. I try to make an update next week. I have some free days maybe I find some time to make a proper update :)

**Comment by TheDevelolper** [comment]
Supporting all of these different frameworks must be a heavy burden.

I've got my own project and I've not written generators or executors yet
but I do know a fair bit about Nx.

I'll see if i can contribute some PRs because I'm likely going to use your
lib.

**Comment by DominikPieper** [comment]
I started all these while corona lockdown was still going and no child on the horizon yet. Some years later it’s harder to find enough time to keep going in the same speed like the whole Nx team 😅

**Comment by pawel-twardziak** [comment]
Hi guys :)

ooo congrats @DominikPieper ! 😍 I did not know you are a full time daddy :) So, we might need to help you out with maintaining the repo, right @TheDevelolper ? 😃 

I am working on the Stencil part there #1101 , you @TheDevelolper  could work on the Solid part :)
