### ISSUE TITLE
Creating a Ionic App fails with InvalidInputOptions [Error]

### ISSUE THREAD

**Issue by kerosin** [nxext/nx-extensions#158]
If I call ```nx g @nxext/stencil:ionic-app my-app``` and chose "SASS" I get an error:

> InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"project":"my-app","appName":"my-app"}
> Errors:
> 
>   **Data path "" should have required property 'npmClient'.**

Full log:
```
C:\src\project>nx g @nxext/stencil:ionic-app my-app
? Which stylesheet format would you like to use? SASS(.scss)       [ http://sass-lang.com          ]
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"project":"my-app","appName":"my-app"}
Errors:

  Data path "" should have required property 'npmClient'.
    at MapSubscriber.project (C:\src\project\node_modules\@angular-devkit\schematics\tools\schema-option-transform.js:32:27)
    at MapSubscriber._next (C:\src\project\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (C:\src\project\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (C:\src\project\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (C:\src\project\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeSubscriber._next (C:\src\project\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (C:\src\project\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (C:\src\project\node_modules\rxjs\internal\operators\mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (C:\src\project\node_modules\rxjs\internal\innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (C:\src\project\node_modules\rxjs\internal\Subscriber.js:66:18) {
  errors: [
    {
      keyword: 'required',
      dataPath: '',
      schemaPath: '#/required',
      params: [Object],
      message: "should have required property 'npmClient'"
    }
  ]
}

```

**Comment by DominikPieper** [comment]
Right now you need to specify the npmClient "--npmClient=yarn".

I added a fix already to to find it out automatically
