### ISSUE TITLE
Error to build a library

### ISSUE THREAD

**Issue by raisiqueira** [nxext/nx-extensions#161]
Hi, i've created a lib with StencilJS into a clean NX project (using OSS template), but when i run the build command the following error appears:

```bash
nx run core:build --debug --verbose 
Cannot find module '@nrwl/workspace/src/utils/fileutils'
Require stack:
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/src/builders/stencil-runtime/stencil-runtime.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/src/builders/stencil-runtime/index.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/src/builders/build/builder.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/node_modules/@angular-devkit/architect/node/index.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/src/commands/run.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/index.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/cli/lib/run-cli.js
Error: Cannot find module '@nrwl/workspace/src/utils/fileutils'
Require stack:
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/src/builders/stencil-runtime/stencil-runtime.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/src/builders/stencil-runtime/index.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/src/builders/build/builder.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/node_modules/@angular-devkit/architect/node/index.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/src/commands/run.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/index.js
- /home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/cli/lib/run-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module.require (/home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/tao/src/compat/compat.js:7:40)
    at Module.require (/home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/node_modules/@nrwl/tao/src/compat/compat.js:7:40)
    at Module.require (/home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nrwl/devkit/node_modules/@nrwl/tao/src/compat/compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/rsiqueira/projects/nx-oss-template/stencil-project/node_modules/@nxext/stencil/src/builders/stencil-runtime/stencil-runtime.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
error Command failed with exit code 1.
```

Dependecies and devDependecies:

```json

  "dependencies": {},
  "devDependencies": {
    "@angular-devkit/schematics": "^11.1.2",
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@commitlint/prompt-cli": "^11.0.0",
    "@jscutlery/semver": "^1.2.0",
    "@justa/prettier-rules": "^0.0.1",
    "@nrwl/cli": "11.2.9",
    "@nrwl/jest": "11.2.9",
    "@nrwl/tao": "11.2.9",
    "@nrwl/workspace": "11.2.9",
    "@nxext/stencil": "^11.0.0",
    "@stencil/core": "^2.3.0",
    "@stencil/sass": "1.4.1",
    "@types/jest": "26.0.8",
    "@types/node": "12.12.38",
    "@types/puppeteer": "~3.0.2",
    "dotenv": "6.2.0",
    "husky": "^4.3.8",
    "jest": "26.2.2",
    "prettier": "2.2.1",
    "pretty-quick": "^3.1.0",
    "puppeteer": "~5.3.1",
    "ts-jest": "26.4.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.0.3"
  },
```

**Comment by raisiqueira** [comment]
I compared NX 10.3.x and 11.2.x versions and saw that `fileUtils` don't exists more. I'll downgrade my workspace to NX 10.3.x and try another build.

https://github.com/nrwl/nx/compare/10.3.x...11.0.0

**Comment by DominikPieper** [comment]
Thanks for the report. Yes, you're right. With 11.0 it wasn't a problem yet. Maybe something new with the 11.2 release

**Comment by raisiqueira** [comment]
> Thanks for the report. Yes, you're right. With 11.0 it wasn't a problem yet. Maybe something new with the 11.2 release

Nice, i was already making a fork of the project to submit a PR.

**Comment by DominikPieper** [comment]
The new version renamed utils to utilities

**Comment by raisiqueira** [comment]
Already on NPM?

**Comment by raisiqueira** [comment]
Fixed version: https://www.npmjs.com/package/@nxext/stencil/v/11.2.0
