### ISSUE TITLE
Support nx 13

### ISSUE THREAD

**Issue by marucjmar** [nxext/nx-extensions#328]
This plugin not supported nx v13. When migrated to v13 build command return error.

```
project_graph_1.createProjectGraph
```
This error exists because now `createProjectGraph` function not exists in https://github.com/nrwl/nx/blob/6017a05274d0e8b206809048c7504494f37f3100/packages/workspace/src/core/project-graph/project-graph.ts

**Comment by DominikPieper** [comment]
@marucjmar v13 for all plugins available

**Comment by emrehayirci** [comment]
```
{
  "name": "--",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "start-frontend": "nx build frontend",
    "serve-frontend": "nx serve frontend",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "devDependencies": {
    "@angular-devkit/architect": "^0.1202.12",
    "@angular-devkit/core": "^12.2.9",
    "@angular-devkit/schematics": "^12.2.9",
    "@nrwl/cli": "13.1.2",
    "@nrwl/cypress": "13.1.2",
    "@nrwl/eslint-plugin-nx": "13.1.2",
    "@nrwl/jest": "13.1.2",
    "@nrwl/linter": "13.1.2",
    "@nrwl/nx-cloud": "12.5.2",
    "@nrwl/tao": "13.1.2",
    "@nrwl/workspace": "13.1.2",
    "@nx-python/nx-python": "^1.0.3",
    "@nxext/svelte": "^13.0.0",
    "@testing-library/svelte": "^3.0.3",
    "@tsconfig/svelte": "^1.0.10",
    "@types/jest": "27.0.2",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "~4.31.1",
    "@typescript-eslint/parser": "~4.31.1",
    "cypress": "^8.3.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-svelte3": "^3.1.2",
    "jest": "27.2.3",
    "postcss": "^8.3.9",
    "prettier": "^2.3.1",
    "rollup-plugin-local-resolve": "^1.0.7",
    "sass": "^1.42.1",
    "svelte": "^3.42.1",
    "svelte-check": "^1.4.0",
    "svelte-jester": "^1.3.2",
    "svelte-preprocess": "^4.9.8",
    "ts-jest": "27.0.5",
    "typescript": "~4.3.5"
  },
  "dependencies": {
    "nx": "^13.1.2",
    "svelte-materialify": "0.3.4",
    "tslib": "^2.0.0"
  }
}

```
Hello @marucjmar thanks for your reply. I migrated nx to the latest, cleared node_modules and re_installed again  all my dependencies and re-run again. 
Outcome is the same, here is the verbose output of `nx serve frontend`:
```
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at createRollupOptions (/Users/local/Desktop/bormobi/node_modules/@nxext/svelte/src/executors/utils/rollup-options.js:90:29)
    at /Users/local/Desktop/bormobi/node_modules/@nxext/svelte/src/executors/build/builder.js:27:72
    at Generator.next (<anonymous>)
    at fulfilled (/Users/local/Desktop/bormobi/node_modules/tslib/tslib.js:114:62)
``` 

My configration is failing at https://github.com/nxext/nx-extensions/blob/main/packages/svelte/src/executors/utils/rollup-options.ts#L119

It looks for options.headers, options object has the type of https://github.com/nxext/nx-extensions/blob/12f4b1c4371e595f94c92eeefdfcd49e12669f66/packages/svelte/src/executors/build/schema.d.ts#L31
And I didn't see headers in the type description, or found a documentation to set them. 

Here is my svelte.config.cjs:
```
const sveltePreprocess = require('svelte-preprocess');

const config = {
    compilerOptions: {},
    preprocess: sveltePreprocess(),
}
module.exports = config; 
```

**Comment by DominikPieper** [comment]
The strange thing is that this line affects your build at all just after the update. I'll at a check for that line, but it's been there since May. ^^'

**Comment by DominikPieper** [comment]
@emrehayirci could you update and re-test, please?

**Comment by emrehayirci** [comment]
@DominikPieper Thanks a lot! Everything works well with the new release :)
