### ISSUE TITLE
Stencil: Storybook Unable to compile Typescript

### ISSUE THREAD

**Issue by Freytag** [nxext/nx-extensions#820]
**Describe the bug**
After creating a new NX workspace and setting up a stencil project with `@nxext/stencil` after adding Storybook `@nxext/stencil:storybook-configuration` [per the docs ](https://github.com/nxext/nx-extensions/tree/main/packages/stencil#storybook). I get the following output and TS error. 

```bash
> nx run core-components:storybook

@nrwl/workspace:run-commands is deprecated and will be removed in Nx 16. Please switch to nx:run-commands
> nx run core-components:serve
> nx run core-components:serve-storybook
[41:05.6]  build, core-components, prod mode, started ...
[41:05.6]  transpile started ...
[41:05.7]  transpile finished in 86 ms
[41:05.7]  copy started ...
[41:05.7]  generate custom elements started ...
[41:05.7]  generate lazy started ...
[41:05.8]  copy finished (0 files) in 138 ms
info @storybook/html v6.5.12
info 
[41:06.0]  generate custom elements finished in 329 ms
[41:06.4]  generate lazy finished in 745 ms
[41:06.5]  build finished, watching for changes... in
           915 ms
[41:06.5]  http://localhost:3340/
ERR! TSError: ⨯ Unable to compile TypeScript:
ERR! .storybook/main.ts(47,30): error TS2345: Argument of type 'TsconfigPathsPlugin' is not assignable to parameter of type 'ResolvePluginInstance | "..."'.
ERR!   Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance'.
ERR!     Types of property 'apply' are incompatible.
ERR!       Type '(resolver: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void' is not assignable to type '(resolver: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void'.
ERR!         Types of parameters 'resolver' and 'resolver' are incompatible.
ERR!           Type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver' is not assignable to type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver'.
ERR!             The types of 'options.plugins' are incompatible between these types.
ERR!               Type 'Plugin[]' is not assignable to type 'Plugin[]'. Two different types with this name exist, but they are unrelated.
ERR!                 Type 'Plugin' is not assignable to type 'Plugin'. Two different types with this name exist, but they are unrelated.
ERR!                   Type '{ apply: (arg0: Resolver) => void; }' is not assignable to type 'Plugin'.
ERR!                     Type '{ apply: (arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void; }' is not assignable to type '{ apply: (arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void; }'.
ERR!                       Types of property 'apply' are incompatible.
ERR!                         Type '(arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void' is not assignable to type '(arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void'.
ERR!                           Types of parameters 'arg0' and 'arg0' are incompatible.
ERR!                             Type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver' is not assignable to type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver'.
ERR!                               Types of property 'options' are incompatible.
ERR!                                 Property 'extensionAlias' is missing in type 'ResolveOptions' but required in type 'ResolveOptionsTypes'.
ERR! .storybook/main.ts(48,29): error TS2322: Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance | "..."'.
ERR! 
ERR!     at createTSError (/Users/mfreyt175/git/playground/ent-web-ui/node_modules/ts-node/src/index.ts:859:12)
ERR!     at reportTSError (/Users/mfreyt175/git/playground/ent-web-ui/node_modules/ts-node/src/index.ts:863:19)
ERR!     at getOutput (/Users/mfreyt175/git/playground/ent-web-ui/node_modules/ts-node/src/index.ts:1077:36)
ERR!     at Object.compile (/Users/mfreyt175/git/playground/ent-web-ui/node_modules/ts-node/src/index.ts:1433:41)
ERR!     at Module.m._compile (/Users/mfreyt175/git/playground/ent-web-ui/node_modules/ts-node/src/index.ts:1617:30)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
ERR!     at Object.require.extensions.<computed> [as .ts] (/Users/mfreyt175/git/playground/ent-web-ui/node_modules/ts-node/src/index.ts:1621:12)
ERR!     at Module.load (node:internal/modules/cjs/loader:1027:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1051:19)
ERR!  .storybook/main.ts(47,30): error TS2345: Argument of type 'TsconfigPathsPlugin' is not assignable to parameter of type 'ResolvePluginInstance | "..."'.
ERR!   Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance'.
ERR!     Types of property 'apply' are incompatible.
ERR!       Type '(resolver: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void' is not assignable to type '(resolver: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void'.
ERR!         Types of parameters 'resolver' and 'resolver' are incompatible.
ERR!           Type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver' is not assignable to type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver'.
ERR!             The types of 'options.plugins' are incompatible between these types.
ERR!               Type 'Plugin[]' is not assignable to type 'Plugin[]'. Two different types with this name exist, but they are unrelated.
ERR!                 Type 'Plugin' is not assignable to type 'Plugin'. Two different types with this name exist, but they are unrelated.
ERR!                   Type '{ apply: (arg0: Resolver) => void; }' is not assignable to type 'Plugin'.
ERR!                     Type '{ apply: (arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void; }' is not assignable to type '{ apply: (arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void; }'.
ERR!                       Types of property 'apply' are incompatible.
ERR!                         Type '(arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void' is not assignable to type '(arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void'.
ERR!                           Types of parameters 'arg0' and 'arg0' are incompatible.
ERR!                             Type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver' is not assignable to type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver'.
ERR!                               Types of property 'options' are incompatible.
ERR!                                 Property 'extensionAlias' is missing in type 'ResolveOptions' but required in type 'ResolveOptionsTypes'.
ERR! .storybook/main.ts(48,29): error TS2322: Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance | "..."'.
ERR! 
WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
 >  NX   ⨯ Unable to compile TypeScript:
   .storybook/main.ts(47,30): error TS2345: Argument of type 'TsconfigPathsPlugin' is not assignable to parameter of type 'ResolvePluginInstance | "..."'.
     Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance'.
       Types of property 'apply' are incompatible.
         Type '(resolver: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void' is not assignable to type '(resolver: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void'.
           Types of parameters 'resolver' and 'resolver' are incompatible.
             Type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver' is not assignable to type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver'.
               The types of 'options.plugins' are incompatible between these types.
                 Type 'Plugin[]' is not assignable to type 'Plugin[]'. Two different types with this name exist, but they are unrelated.
                   Type 'Plugin' is not assignable to type 'Plugin'. Two different types with this name exist, but they are unrelated.
                     Type '{ apply: (arg0: Resolver) => void; }' is not assignable to type 'Plugin'.
                       Type '{ apply: (arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void; }' is not assignable to type '{ apply: (arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void; }'.
                         Types of property 'apply' are incompatible.
                           Type '(arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver) => void' is not assignable to type '(arg0: import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void'.
                             Types of parameters 'arg0' and 'arg0' are incompatible.
                               Type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver' is not assignable to type 'import("/Users/mfreyt175/git/playground/ent-web-ui/node_modules/webpack/types").Resolver'.
                                 Types of property 'options' are incompatible.
                                   Property 'extensionAlias' is missing in type 'ResolveOptions' but required in type 'ResolveOptionsTypes'.
   .storybook/main.ts(48,29): error TS2322: Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance | "..."'.
   
   Pass --verbose to see the stacktrace.
 
 >  NX   Running target "core-components:serve-storybook" failed
   Failed tasks:
   
   - core-components:serve-storybook
   ```

**To Reproduce**

1. `npx create-nx-workspace@latest`
2. `npm install @nxext/stencil @nrwl/storybook --save-dev`
3. `nx g @nxext/stencil:lib core-components --buildable`
4. `nx g @nxext/stencil:storybook-configuration core-components`
5. `nx build core-components`
6. `nx storybook core-components`

**Expected behavior**
Storybook to successfully run and not have any TS errors

**Additional context**

I have tried this on  `Node : 14.11.0` with `npm  : 6.14.8` and even on `Node: 16.17.1` with `npm: 8.15.0` and get the same results. 

```bash
   Node : 14.11.0
   OS   : darwin x64
   npm  : 6.14.8
   
   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : Not Found
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nxext/stencil: 14.0.6
```

**Comment by Freytag** [comment]
I've also tried nx-workspace@14.5.0 since i see that the stencil package uses those versions. I also installed @nrwl/storybook@14.5.0 so it would match this repo as well. but still seeing the same issue.

**Comment by oben01** [comment]
Hello @Freytag 
u can use type assertion to modify tsPaths const of  `./storybook/main.ts` file.
something like this : 

```typescript
const tsPaths = new TsconfigPathsPlugin({
configFile: './tsconfig.base.json',
extensions: resolve.extensions,
mainFields: resolve.mainFields as string[],
}) as "..." | ResolvePluginInstance;
```

The `ResolvePluginInstance` is imported from webpack 
```typescript
import type { Configuration, RuleSetRule, ResolvePluginInstance } from 'webpack';
``` 

i hope this helps

**Comment by Freytag** [comment]
> Hello @Freytag u can use type assertion to modify tsPaths const of `./storybook/main.ts` file. something like this :
> 
> ```ts
> const tsPaths = new TsconfigPathsPlugin({
> configFile: './tsconfig.base.json',
> extensions: resolve.extensions,
> mainFields: resolve.mainFields as string[],
> }) as "..." | ResolvePluginInstance;
> ```
> 
> The `ResolvePluginInstance` is imported from webpack
> 
> ```ts
> import type { Configuration, RuleSetRule, ResolvePluginInstance } from 'webpack';
> ```
> 
> i hope this helps

Thanks for the suggestion @oben01. This does resolve the TS Error. I'll have to see where to suggest thus update to happen. 

However, I now have another issue.  Any thoughts on this issue? 
```bash
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Running in webpack instance: 5.74.0
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
(node:18651) UnhandledPromiseRejectionWarning: file:///Users/mfreyt175/git/playground/ent-web-ui/node_modules/@babel/helper-define-polyfill-provider/esm/index.node.mjs:1
import { declare } from '@babel/helper-plugin-utils';
         ^^^^^^^
SyntaxError: The requested module '@babel/helper-plugin-utils' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
```

**Comment by oben01** [comment]
@Freytag could u provide a repo please ? I cannot reproduce locally

**Comment by Freytag** [comment]
> @Freytag could u provide a repo please ? I cannot reproduce locally

Interesting that you are unable to reproduce with the **Steps to reproduce the behavior**. Here is a repo, [nx-stencil](https://github.com/Freytag/nx-stencil), created following the steps above to reproduce.  I also added in your fix for the TS error.

**Comment by oben01** [comment]
@Freytag 
I got some erros in the console when running `nx storybook core-components`
```
ERR! Error: Cannot find module 'react/package.json'
ERR! Require stack:
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/presets/preview-preset.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/src/config/workspaces.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/src/command-line/run.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/bin/run-executor.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
ERR!     at _default (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js:202:46)
ERR!     at async starterGeneratorFn (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:116:16)
ERR!     at async Object.start (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:272:14)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  Error: Cannot find module 'react/package.json'
ERR! Require stack:
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/presets/preview-preset.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/src/config/workspaces.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/src/command-line/run.js
ERR! - /home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/bin/run-executor.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
ERR!     at _default (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js:202:46)
ERR!     at async starterGeneratorFn (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:116:16)
ERR!     at async Object.start (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:272:14)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/builder-webpack5/dist/cjs/presets/preview-preset.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-common/dist/cjs/presets.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-common/dist/cjs/index.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/src/config/workspaces.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/src/command-line/run.js',
ERR!     '/home/CENTRO_odahmaz/IdeaProjects/nx-stencil/node_modules/nx/bin/run-executor.js'
ERR!   ]
ERR! }
```
However the storybook is running 

![image](https://user-images.githubusercontent.com/22369027/195260325-7fa03976-2f6e-458a-bbce-f1d4bc4d6e93.png)

node version : `v14.16.1`
npm version : `6.14.12`

nx report : 
```

 >  NX   Report complete - copy this into the issue template

   Node : 14.16.1
   OS   : linux x64
   npm  : 6.14.12
   
   nx : 14.8.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.3
   @nrwl/js : Not Found
   @nrwl/linter : 14.8.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.3
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 14.8.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nxext/stencil: 14.0.6

```
I'll give it a try on my macbook and get back to u. 
Did u try scss stylesheet ?

**Comment by Freytag** [comment]
@oben01 That's and interesting error that it's trying to find some `react/package.json` 
I haven't tried all the stylesheet configurations. But when i originally started i tried PostCSS and had issues so i figured CSS should be the ones with the least amount of configuration since its just CSS and doesn't require pre-processors.

**Comment by bogusweb** [comment]
any update? managed to fix it somehow?
