### ISSUE TITLE
Stencil | Cannot create buildable, publishable library with directory and importPath options

### ISSUE THREAD

**Issue by tibiiorcdw** [nxext/nx-extensions#867]
**Describe the bug**
Creating a library with directory, buildable, and publishable values fails to generate lib.

**To Reproduce**
_npx nx g @nxext/stencil:library --name=core-components-web --directory=shared/ui --importPath=@cdw-ui/core-components-web --buildable=true_

**Expected behavior**
It would create the library at the provided directory.

**Additional context**

**nx: 15.3.3
@nxext/stencil: 15.0.0**

Output from the command window:

_>  NX  Generating @nxext/stencil:library

√ Which stylesheet format would you like to use? · css

 >  NX   Cannot find configuration for 'shared-ui-core-components-web'

Error: Cannot find configuration for 'shared-ui-core-components-web'
    at readProjectConfiguration (D:\Git\design-system-ui-core\node_modules\nx\src\generators\utils\project-configuration.js:156:15)
    at normalize (D:\Git\design-system-ui-core\node_modules\@nxext\stencil\src\generators\make-lib-buildable\make-lib-buildable.js:13:65)
    at D:\Git\design-system-ui-core\node_modules\@nxext\stencil\src\generators\make-lib-buildable\make-lib-buildable.js:32:25
    at Generator.next (<anonymous>)
    at D:\Git\design-system-ui-core\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\Git\design-system-ui-core\node_modules\tslib\tslib.js:114:16)
    at makeLibBuildableGenerator (D:\Git\design-system-ui-core\node_modules\@nxext\stencil\src\generators\make-lib-buildable\make-lib-buildable.js:31:20)
    at D:\Git\design-system-ui-core\node_modules\@nxext\stencil\src\generators\library\generator.js:55:52
    at Generator.next (<anonymous>)_

**Comment by DominikPieper** [comment]
@sebastiandg7 help of appreciated every time. I do all the development in my spare time and can need any help
