### ISSUE TITLE
Solid: unable install

### ISSUE THREAD

**Issue by SinnerAir** [nxext/nx-extensions#895]
**Describe the bug**
Unable to install package for new version of Nx (15)

**To Reproduce**
1. Call command: `npx create-nx-workspace@latest myorg --preset=ts`
2. Call command: `npm install @nxext/solid --save-dev`

**Expected behavior**
Install success.

**Additional context**
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: advant-next@0.0.0
npm ERR! Found: @nrwl/workspace@15.6.2
npm ERR! node_modules/@nrwl/workspace
npm ERR!   dev @nrwl/workspace@"15.6.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nrwl/workspace@"^14.5.0" from @nxext/solid@14.0.2
npm ERR! node_modules/@nxext/solid
npm ERR!   dev @nxext/solid@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by darrenbarklie** [comment]
Also cannot get started with Solid, using the following commands in a new directory:

```
npx create-nx-workspace@latest nx-default --preset=npm

npm install @nxext/solid --save-dev

nx g @nxext/solid:application solid-app --dry-run
```
Returns:
```
Cannot read properties of undefined (reading '@nrwl/workspace')

TypeError: Cannot read properties of undefined (reading '@nrwl/workspace')
    at readNxVersion (/Users/daz/Code/nx-default/node_modules/@nxext/solid/src/generators/init/lib/util.js:9:35)
    at addJestPlugin (/Users/daz/Code/nx-default/node_modules/@nxext/solid/src/generators/init/lib/add-jest-plugin.js:12:52)
    at /Users/daz/Code/nx-default/node_modules/@nxext/solid/src/generators/init/init.js:16:66
    at Generator.next (<anonymous>)
    at /Users/daz/Code/nx-default/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/daz/Code/nx-default/node_modules/tslib/tslib.js:163:16)
    at initGenerator (/Users/daz/Code/nx-default/node_modules/@nxext/solid/src/generators/init/init.js:13:20)
    at /Users/daz/Code/nx-default/node_modules/@nxext/solid/src/generators/application/application.js:37:57
    at Generator.next (<anonymous>)
```

**Comment by DominikPieper** [comment]
@darrenbarklie I've to do some tests. I never yoused the npm preset. The plugins assume that there's @nrwl/workspace present. They are designed to primary work with an integrated workspace

**Comment by darrenbarklie** [comment]
Hi @DominikPieper — maybe I misconfigured this.  I've revisited this and since ran the following:
```
npx create-nx-workspace@latest nx-solid --preset=ts

cd nx-solid

npm install @nxext/solid --save
```
I can confirm same dependency issue as @SinnerAir 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nx-solid@0.0.0
npm ERR! Found: @nrwl/workspace@15.7.2
npm ERR! node_modules/@nrwl/workspace
npm ERR!   dev @nrwl/workspace@"15.7.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nrwl/workspace@"^14.5.0" from @nxext/solid@14.0.2
npm ERR! node_modules/@nxext/solid
npm ERR!   @nxext/solid@"*" from the root project
```

**Comment by tatems** [comment]
I'm running into a similar issue installing the `beta` tag (`15.1.0`), however it's failing to find the matching: `nxext/vite` package:
```bash
❯ npm install @nxext/solid@beta --save-dev
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nxext/vite@^15.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[USER]/.npm/_logs/2023-02-21T20_40_36_722Z-debug-0.log
```
