### ISSUE TITLE
Svelte: Cannot read properties of undefined (reading '@nrwl/workspace')

### ISSUE THREAD

**Issue by mibzman** [nxext/nx-extensions#931]
**Describe the bug**
The svelte generator does not work out of the box.  When I run it I get:
`NX   Cannot read properties of undefined (reading '@nrwl/workspace')`

**To Reproduce**
```
npx create-nx-workspace@latest nx-svelte-example;
cd nx-svelte-example;
npm install @nxext/svelte --save-dev;
nx g @nxext/svelte:app web;
```

**Additional context**
Full stacktrace:
```
TypeError: Cannot read properties of undefined (reading '@nrwl/workspace')
    at readNxVersion (/home/sam/beryl/test/nxtest/svelte/node_modules/@nxext/svelte/src/generators/utils/utils.js:9:35)
    at addJestPlugin (/home/sam/beryl/test/nxtest/svelte/node_modules/@nxext/svelte/src/generators/init/lib/add-jest-plugin.js:16:53)
    at /home/sam/beryl/test/nxtest/svelte/node_modules/@nxext/svelte/src/generators/init/init.js:15:62
    at Generator.next (<anonymous>)
    at /home/sam/beryl/test/nxtest/svelte/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/sam/beryl/test/nxtest/svelte/node_modules/tslib/tslib.js:163:16)
    at initGenerator (/home/sam/beryl/test/nxtest/svelte/node_modules/@nxext/svelte/src/generators/init/init.js:13:20)
    at /home/sam/beryl/test/nxtest/svelte/node_modules/@nxext/svelte/src/generators/application/application.js:37:57
    at Generator.next (<anonymous>)
```

**Comment by DominikPieper** [comment]
@mibzman what’s your Nx version? The plugin isn’t Nx 16 compatible yet

**Comment by alec-c4** [comment]
@mibzman Hey! I have the same error. May I ask you about plans top add support for NX 16?

**Comment by DominikPieper** [comment]
There are some minor adjustments needed. After that, the V16 will be released

**Comment by fivehanz** [comment]
@DominikPieper any updates on when / ETA it will be released?
