### ISSUE TITLE
Sveltekit: Cannot generate application

### ISSUE THREAD

**Issue by Soulusions** [nxext/nx-extensions#944]
**Describe the bug**
Generating a new Sveltekit application fails.

**To Reproduce**
Run `pnpm exec nx generate @nxext/sveltekit:application svelte-app` in a newly create nx repo.

**Expected behavior**
Running generate should generate the project and not error out.

**Additional context**
Here's the CLI output with the verbose flag:
```
>  NX  Generating @nxext/sveltekit:application


 >  NX   (0 , project_configuration_1.shouldDefaultToUsingStandaloneConfigs) is not a function


TypeError: (0 , project_configuration_1.shouldDefaultToUsingStandaloneConfigs) is not a function
    at getWorkspaceLayout (/home/soul/nn-nx/node_modules/.pnpm/@nrwl+devkit@14.8.8_nx@16.1.4_typescript@4.9.5/node_modules/@nrwl/devkit/src/utils/get-workspace-layout.js:25:96)
    at normalizeOptions (/home/soul/nn-nx/node_modules/.pnpm/@nxext+sveltekit@14.0.0-next.2_nx@16.1.4_typescript@4.9.5/node_modules/@nxext/sveltekit/src/generators/application/generator.js:19:60)
    at /home/soul/nn-nx/node_modules/.pnpm/@nxext+sveltekit@14.0.0-next.2_nx@16.1.4_typescript@4.9.5/node_modules/@nxext/sveltekit/src/generators/application/generator.js:36:25
    at Generator.next (<anonymous>)
    at /home/soul/nn-nx/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/soul/nn-nx/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:163:16)
    at applicationGenerator (/home/soul/nn-nx/node_modules/.pnpm/@nxext+sveltekit@14.0.0-next.2_nx@16.1.4_typescript@4.9.5/node_modules/@nxext/sveltekit/src/generators/application/generator.js:35:20)
    at Object.<anonymous> (/home/soul/nn-nx/node_modules/.pnpm/nx@16.1.4/node_modules/nx/src/command-line/generate.js:249:36)
    at Generator.next (<anonymous>)
```
On an additional note, I am using pnpm.

**Comment by t-mish** [comment]
I think it will be resolved soon. There is a pull request which actually integrates new Nx's vite instead of the deprecated nxext one. Hope it will be published in near future

**Comment by skapoor8** [comment]
Having the exact same issue. Any updates on this?
